ucene_query = { white_space } node {node} | { white_space } | EOF ;

node = operator_exp EOF 
       | operator_exp group_exp { operator_exp } { node } 
       | operator_exp node 
       | group_exp { operator_exp } { node } ;

group_exp = field_term { white_space } | parent_exp

parent_exp = "("  { white_space } node { node } ")"

field_term = unquoted_term eq_oper_exp {white_space} range_operator_exp
            | unquoted_term eq_oper_exp {white_space} parent_exp
            | unquoted_term (eq_oper_exp | range_oper_exp) {white_space} term


term = prefix_operator_exp quoted_term [ proximity_modifier ] [ boost_modifier ] { white_space }
        | prefix_operator_exp regex_term { white_space }
        | prefix_operator_exp unquoted_term [ fuzzy_modifier ] [ boost_modifier ] { white_space }

rterm_char = "\\" EscapeChar | '.' | [^ \t\r\n\f\{\}()"/^~\[\]]

ranged_term = rterm_char { rterm_char }

unquoted_term = UnquotedChar { UnquotedChar } 

quoted_term = """ { QuotedChar } """

regex_term = "/" RegexChar { RegexChar } "/"

UnquotedChar = "\\" EscapeChar | "." | [^ \t\r\n\f\{\}()"/^~\[\]]

QuotedChar = -(""" | "//") "."  | "\\" EscapeChar

RegexChar = -("/" / "\\") . | "\\" EscapeChar

EscapeChar = "+"  | "-" | "!" | "(" | ")" | "{" | "}" | "["
                | "]" | "^" | "\"" | "?"| ":" | "\\" | "&" | "|"
                | "'" | "/" | "~" | "*" | " "

proximity_modifier = "~" int_exp

boost_modifier = "^" decimal_or_int_exp

fuzzy_modifier = "~" [ decimal_exp ]

decimal_or_int_exp = decimal_exp | int_exp

decimal_exp = "0." int_exp

int_exp = int { int }

int = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

range_operator_exp = "[" ranged_term { white_space } "TO" white_space { white_space } ranged_term "]"
                   | "[" ranged_term { white_space } "TO" white_space { white_space } ranged_term "}"
                   | "{" ranged_term { white_space } "TO" white_space { white_space } ranged_term "]"
                   | "{" ranged_term { white_space } "TO" white_space { white_space } ranged_term "}"      

eq_oper_exp = ":"

range_oper_exp = ":>" | ":<" | ":>=" | ":<="

operator_exp = { white_space } ("AND" | "OR" | "NOT" | "AND NOT" | "OR NOT") white_space { white_space } 

prefix_operator_exp = { white_space } ( "+" | "-" | "!" )

white_space = " " | "\t" | "\r" | "\f"

EOF = "\n"










