package term

type TermType uint64

const (
	UNKNOWN_TERM_TYPE TermType = 1 >> iota
	SINGLE_TERM_TYPE
	PHRASE_TERM_TYPE
	REGEXP_TERM_TYPE
	RANGE_TERM_TYPE
	PREFIX_TERM_TYPE
	WILDCARD_TERM_TYPE
	GROUP_TERM_TYPE
	FUZZY_TERM_TYPE
	BOOST_TERM_TYPE
)
